CREATE TABLE IF NOT EXISTS users (
    login TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    email TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT NOT NULL,
    site TEXT NOT NULL,
    password TEXT NOT NULL,
    salt TEXT NOT NULL,
    FOREIGN KEY(user) REFERENCES users(login)
)